import assert from 'assert';
import path from 'path';
import fs from 'fs';

process.env.NODE_ENV = 'test';

import { buildProject } from '../../bin/commands/build.js';

try {
  console.log('🧪 Testing Pre-build and Post-build Lifecycle Hooks (#866)...');

  const testTmpDir = path.join(process.cwd(), '.test_build_hooks_tmp');
  if (fs.existsSync(testTmpDir)) {
    fs.rmSync(testTmpDir, { recursive: true, force: true });
  }
  fs.mkdirSync(testTmpDir, { recursive: true });

  const srcDir = path.join(testTmpDir, 'src');
  fs.mkdirSync(srcDir, { recursive: true });

  // Minimal component template for compilation
  fs.writeFileSync(path.join(srcDir, 'App.component.html'), '<div>Hook Test App</div>', 'utf8');
  fs.writeFileSync(path.join(srcDir, 'App.component.js'), `
    export default {
      name: 'App'
    };
  `, 'utf8');

  const logFile = path.join(testTmpDir, 'hooks_execution.log');

  const createMockCli = (hooksConfig = {}) => ({
    baseDir: testTmpDir,
    config: {
      srcDir: 'src',
      distDir: 'dist',
      templatesDir: '.avenxtemplates',
      rootDir: testTmpDir,
      hooks: hooksConfig,
      server: { port: 3000, host: 'localhost', liveReload: true },
      style: { preprocessor: 'none' },
      debug: { debugReactivity: false },
      voidTags: [],
      warnings: {},
    },
  });

  try {
    // ----------------------------------------------------
    // Test 1: Prebuild and Postbuild hooks run in sequence
    // ----------------------------------------------------
    console.log('  Testing prebuild and postbuild hooks execution sequence...');
    const prebuildFile = path.join(testTmpDir, 'prebuild_done.txt');
    const postbuildFile = path.join(testTmpDir, 'postbuild_done.txt');

    const cli = createMockCli({
      prebuild: `node -e "require('fs').writeFileSync('${prebuildFile.replace(/\\/g, '/')}', 'pre', 'utf8')"`,
      postbuild: `node -e "require('fs').writeFileSync('${postbuildFile.replace(/\\/g, '/')}', 'post', 'utf8')"`,
    });

    buildProject(cli);

    assert.ok(fs.existsSync(prebuildFile), 'prebuild hook should have created prebuild_done.txt');
    assert.ok(fs.existsSync(postbuildFile), 'postbuild hook should have created postbuild_done.txt');
    assert.strictEqual(fs.readFileSync(prebuildFile, 'utf8'), 'pre');
    assert.strictEqual(fs.readFileSync(postbuildFile, 'utf8'), 'post');

    // Verify dist build was created
    const distDir = path.join(testTmpDir, 'dist');
    assert.ok(fs.existsSync(distDir), 'dist directory should have been generated by compiler');

    // ----------------------------------------------------
    // Test 2: Prebuild hook failure halts build
    // ----------------------------------------------------
    console.log('  Testing prebuild hook failure halts compilation and postbuild...');
    const postbuildFailCheck = path.join(testTmpDir, 'should_not_exist.txt');

    const failingCli = createMockCli({
      prebuild: 'node -e "process.exit(1)"',
      postbuild: `node -e "require('fs').writeFileSync('${postbuildFailCheck.replace(/\\/g, '/')}', 'fail', 'utf8')"`,
    });

    assert.throws(() => {
      buildProject(failingCli);
    }, 'buildProject should throw when prebuild hook exits with non-zero code');

    assert.strictEqual(fs.existsSync(postbuildFailCheck), false, 'postbuild should not run if prebuild fails');

    // ----------------------------------------------------
    // Test 3: Empty / missing hooks work safely
    // ----------------------------------------------------
    console.log('  Testing build without hooks runs normally...');
    const emptyHooksCli = createMockCli({});
    buildProject(emptyHooksCli);

    console.log('  ✅ Pre-build and Post-build Lifecycle Hooks tests passed!');
  } finally {
    if (fs.existsSync(testTmpDir)) {
      fs.rmSync(testTmpDir, { recursive: true, force: true });
    }
  }
} catch (error) {
  console.error('❌ Pre-build and Post-build Lifecycle Hooks tests failed!');
  console.error(error);
  process.exit(1);
}
